title: mi blog personal
description: blog dedicado a temas de ingenieria de software
author: Erwin Geovanny Solano Chavez
avatar: /logo.png
email: geovannysolano15@hotmail.es

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
#
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
#
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: logo.png
social:
  name: Shangzhi Huang
  links:
    - https://twitter.com/Synystergeo15
    - https://www.facebook.com/geovanny.solano15
    - https://github.com/
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
